"""add user_id to expenses

Revision ID: 3616f6058988
Revises: 96cd81f740bb
Create Date: 2026-02-01 16:56:54.690702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3616f6058988"
down_revision: Union[str, Sequence[str], None] = "96cd81f740bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "foreignkey_users", "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_constraint("foreignkey_users", type_="foreignkey")
        batch_op.drop_column("user_id")

    op.create_table(
        "users_expenses",
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("expense_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["expense_id"], ["expenses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    # ### end Alembic commands ###
